Add more tests for FilePackage.Headers
artipie/rpm-adapter pull request #187
Opened 2020-05-16 11:20 UTC by victornoel

This is for #155.

In the end I didn't use parametrized tests as proposed by the todo because it was very complex for nothing (and difficulty maintainable I believe)

2020-05-17 09:48 UTC, 0crat commented
This pull request [#187](https://github.com/artipie/rpm-adapter/issues/187) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/c33a1d0d-2ba3-473b-a567-d9ffdc1d9c3d); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

<!-- https://www.0crat.com/footprint/CT2E6TK9B/70e48eb8-74dd-4f40-bd00-021b7194e090, version: 0.53.14, hash: ${buildNumber} -->

2020-05-19 02:52 UTC, carlosmiranda requested changes
@victornoel please see comments

2020-05-19 02:52 UTC, carlosmiranda commented on src/test/java/com/artipie/rpm/pkg/FilePackageHeadersTest.java
> +        final Header header = new Header();
@victornoel let's inline this variable.

2020-05-19 02:52 UTC, carlosmiranda commented on src/test/java/com/artipie/rpm/pkg/FilePackageHeadersTest.java
> +        final Header.HeaderTag tag = Header.HeaderTag.EPOCH;
@victornoel let's inline this variable.

2020-05-19 02:52 UTC, carlosmiranda commented on src/test/java/com/artipie/rpm/pkg/FilePackageHeadersTest.java
> +        final Header header = new Header();
@victornoel let's inline this variable.

2020-05-19 02:52 UTC, carlosmiranda commented on src/test/java/com/artipie/rpm/pkg/FilePackageHeadersTest.java
> +        final Header.HeaderTag tag = Header.HeaderTag.NAME;
@victornoel let's inline this variable.

2020-05-19 18:17 UTC, victornoel commented
@carlosmiranda it is done, thank you

2020-05-19 22:42 UTC, carlosmiranda approved these changes
@victornoel thanks. @g4s8 this is good to merge.

2020-05-20 09:57 UTC, g4s8 approved these changes

2020-05-20 09:57 UTC, merged

2020-05-20 22:27 UTC, carlosmiranda commented
@0crat status

2020-05-21 04:55 UTC, 0crat commented
> @0crat status ([here](https://github.com/artipie/rpm-adapter/issues/187#issuecomment-631761381))

@carlosmiranda This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#187](https://github.com/artipie/rpm-adapter/issues/187) is [in scope](http://www.zerocracy.com/policy.html#14) for 5days
  * The role is `REV`
  * The job is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) for [4days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) will get 25% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @victornoel[/z](https://www.0crat.com/u/victornoel): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Frpm-adapter%23187%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

<!-- https://www.0crat.com/footprint/CT2E6TK9B/449ac020-108a-4c2f-81df-c8bda0618d9b, version: 0.53.14, hash: ${buildNumber} -->

2020-05-21 06:20 UTC, g4s8 commented
@0crat out

2020-05-21 06:22 UTC, 0crat commented
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

<!-- https://www.0crat.com/footprint/CT2E6TK9B/a4982fdb-1b83-489a-a977-84a36ee6b4e5, version: 0.53.14, hash: ${buildNumber} -->

2020-05-21 06:24 UTC, sereshqua commented
@carlosmiranda please make sure during next CR, your comments would be mostly about design problems, but NOT rather cosmetic issues

2020-05-21 06:54 UTC, carlosmiranda commented
@sereshqua confirmed

2020-05-21 07:04 UTC, sereshqua commented
@0crat quality acceptable