For #117: Added assertions to XmlPrimaryTest
artipie/rpm-adapter pull request #202
Opened 2020-05-25 22:32 UTC by paulodamaso

For #117: 
- Added assertions to check if `XmlPrimary` is generating correct XML
- `XmlPrimary` is not generating the file correctly; it has problems in `/metadata[@packages]` and in `/rpm:provides`. I've left two puzzles to fix these errors and add tests to `XmlPrimaryTest`

2020-05-26 06:25 UTC, 0crat commented
This pull request [#202](https://github.com/artipie/rpm-adapter/issues/202) is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/077dac92-0a6e-4420-a3f7-c9b84a8003d3); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

<!-- https://www.0crat.com/footprint/CT2E6TK9B/7260adae-9c0d-4b63-90f5-5d173c0d4074, version: 0.53.14, hash: ${buildNumber} -->

2020-05-27 11:34 UTC, victornoel commented
@0crat status

2020-05-27 11:49 UTC, 0crat commented
> @0crat status  ([here](https://github.com/artipie/rpm-adapter/issues/202#issuecomment-634601419))

@victornoel This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#202](https://github.com/artipie/rpm-adapter/issues/202) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Frpm-adapter%23202%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

<!-- https://www.0crat.com/footprint/CT2E6TK9B/4d5ccff4-6455-403f-86a0-fc7c2afa6b43, version: 0.53.14, hash: ${buildNumber} -->

2020-05-27 13:07 UTC, g4s8 commented
@0crat assign @victornoel

2020-05-27 13:14 UTC, 0crat commented
> @0crat assign @victornoel  ([here](https://github.com/artipie/rpm-adapter/issues/202#issuecomment-634647075))

@g4s8 This pull request [#202](https://github.com/artipie/rpm-adapter/issues/202) is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/da43a845-119a-4a83-a303-12857e88e82c); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

<!-- https://www.0crat.com/footprint/CT2E6TK9B/f5ee57d7-cbc8-4752-a061-f922dc93babe, version: 0.53.14, hash: ${buildNumber} -->

2020-05-27 13:14 UTC, 0crat commented
> @0crat assign @victornoel  ([here](https://github.com/artipie/rpm-adapter/issues/202#issuecomment-634647075))

@g4s8 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@a6481982-e24c-4d53-86e7-af311f6ddbe6, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:artipie/rpm-adapter#202] declared for identity constraint of element "agenda".
```

[0.53.14](https://github.com/zerocracy/farm): CID: [8e65e532-4cad-4759-8921-091c9eecfc5b](https://www.0crat.com/footprint/CT2E6TK9B/8e65e532-4cad-4759-8921-091c9eecfc5b), Type: "Order was given"

<!-- https://www.0crat.com/footprint/CT2E6TK9B/28e65be4-54ca-4359-998b-5e4a2b9e457a, version: 0.53.14, hash: ${buildNumber} -->

2020-05-27 19:25 UTC, victornoel commented
@0crat status

2020-05-27 19:26 UTC, 0crat commented
> @0crat status ([here](https://github.com/artipie/rpm-adapter/issues/202#issuecomment-634890020))

@victornoel This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#202](https://github.com/artipie/rpm-adapter/issues/202) is [in scope](http://www.zerocracy.com/policy.html#14) for 6hr
  * The role is `REV`
  * The job is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel) for [6hr](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @victornoel[/z](https://www.0crat.com/u/victornoel) will get 25% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Frpm-adapter%23202%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

<!-- https://www.0crat.com/footprint/CT2E6TK9B/c3259c87-bce8-49b0-80e4-46b05101bf5f, version: 0.53.15, hash: ${buildNumber} -->

2020-05-28 17:18 UTC, victornoel reviewed
@paulodamaso see my comments

2020-05-28 17:18 UTC, victornoel commented on src/main/java/com/artipie/rpm/meta/XmlPrimary.java
> + *  element generation is fixed.
@paulodamaso maybe actually another test should be added instead of having one giant test, wdyt?

2020-05-28 17:18 UTC, victornoel commented on src/main/java/com/artipie/rpm/meta/XmlPrimary.java
> + *  XmlPrimaryTest.
@paulodamaso same thing here

2020-05-31 15:56 UTC, paulodamaso commented
@victornoel I don't know for sure what is better. I could split these tests in 6 or 7, testing if each part is being added correctly to the xml individually, but I think that they would be redundant since we will also need a test to check if the entire xml is assembled correctly as a whole. So I still prefer to test the latter case only

2020-05-31 16:10 UTC, victornoel requested changes
@paulodamaso yes, I agree. See just one last small comment I left

2020-05-31 16:10 UTC, victornoel commented on src/test/java/com/artipie/rpm/meta/XmlPrimaryTest.java
> +                    new ListOf<String>(
@paulodamaso the type here is not needed I believe

2020-05-31 22:47 UTC, paulodamaso commented
@victornoel Done!

2020-06-01 13:51 UTC, 0crat commented
@victornoel[/z](https://www.0crat.com/u/victornoel) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

<!-- https://www.0crat.com/footprint/CT2E6TK9B/7e560e96-7539-4f0b-afdb-f76837628505, version: 0.53.15, hash: ${buildNumber} -->

2020-06-01 15:19 UTC, victornoel commented
@g4s8 looks good to me

2020-06-01 15:25 UTC, g4s8 approved these changes

2020-06-02 15:48 UTC, merged

2020-06-02 16:09 UTC, 0crat commented
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

<!-- https://www.0crat.com/footprint/CT2E6TK9B/7587ed03-fab4-48ed-a19c-7f3e8cb8211a, version: 0.53.15, hash: ${buildNumber} -->

2020-06-02 20:17 UTC, sereshqua commented
@0crat quality good