#219 - packages attribute in primary
artipie/rpm-adapter pull request #221
Opened 2020-06-03 05:24 UTC by olenagerasimova

For #219: `XmlPrimary` is not responsible for counting packages and setting correct value to `packages` attribute, `Metadata` is, it's done in `brush` method. I've added corresponding assertion to the test and removed todo.

2020-06-03 05:47 UTC, 0crat commented
This pull request [#221](https://github.com/artipie/rpm-adapter/issues/221) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/8ef3fcf5-5b74-4348-8094-862e6bea63f6); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

<!-- https://www.0crat.com/footprint/CT2E6TK9B/38fc31b5-c76a-4770-965d-f9c23688776a, version: 0.53.15, hash: ${buildNumber} -->

2020-06-03 14:38 UTC, paulodamaso requested changes
@olenagerasimova Just one comment, please take a look

2020-06-03 14:38 UTC, paulodamaso commented on src/test/java/com/artipie/rpm/pkg/ModifiableMetadataTest.java
> +                "/*[local-name()='metadata' and @packages='2']"
@olenagerasimova Just to make reading easier, could you please put this `xpath` query on top of the others? It seems more logical that we assert first if some element attributes are correct, then if the children elments are.

2020-06-03 18:41 UTC, olenagerasimova commented
@paulodamaso thanks, corrected, take a look please

2020-06-04 18:25 UTC, olenagerasimova commented
@paulodamaso ping

2020-06-06 21:00 UTC, paulodamaso approved these changes
@olenagerasimova Great, thank you!

2020-06-06 21:01 UTC, paulodamaso commented
@g4s8 please merge

2020-06-08 06:47 UTC, 0crat commented
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

<!-- https://www.0crat.com/footprint/CT2E6TK9B/c81ae271-ed32-453b-bf46-6523cbcc70bd, version: 0.53.15, hash: ${buildNumber} -->

2020-06-08 07:19 UTC, olenagerasimova commented
@g4s8 ping

2020-06-09 16:54 UTC, olenagerasimova commented
@g4s8 could you please approve or merge this?

2020-06-10 13:51 UTC, g4s8 approved these changes

2020-06-10 14:06 UTC, merged

2020-06-11 04:15 UTC, sereshqua commented
@paulodamaso ping

2020-06-11 20:10 UTC, sereshqua commented
@0crat quality acceptable

2020-06-16 17:31 UTC, paulodamaso commented
@sereshqua Sorry for the delay, i'll try to find at least 3 issues in the next CRs

2020-06-16 17:31 UTC, paulodamaso commented
@g4s8 please take a look at this, @0crat lost rtack of this one after QA

2020-06-16 17:34 UTC, 0crat commented
Are you speaking to me or about me [here](https://github.com/artipie/rpm-adapter/issues/221#issuecomment-644906035); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)