Implemented RpmMetadata.Remove
artipie/rpm-adapter pull request #393
Opened 2021-05-11 11:48 UTC by olenagerasimova

Part of #388 
Implemented `RpmMetadata.Remove` class and added corresponding unit-test. The implementation uses temp file to write an intermediate result. We cannot use Pipied io streams here as operations should be performed one by one.

2021-05-11 13:29 UTC, g4s8 requested changes
@olenagerasimova just one comment

2021-05-11 13:29 UTC, g4s8 commented on src/main/java/com/artipie/rpm/RpmMetadata.java
> +                Files.delete(temp);
@olenagerasimova this line is potential cause of resource leaks, so it should be placed in `finally` block

2021-05-11 13:45 UTC, olenagerasimova commented
@g4s8 thanks, corrected

2021-05-11 14:23 UTC, g4s8 approved these changes
@olenagerasimova thanks

2021-05-11 14:23 UTC, merged

2021-05-12 07:26 UTC, olenagerasimova commented
@rultor release, tag=`1.4`

2021-05-12 07:28 UTC, rultor commented
> @rultor release, tag=`1.4`

@olenagerasimova OK, I will release it now. Please check the progress [here](https://www.rultor.com/t/24458-839532547)

2021-05-12 07:39 UTC, rultor commented
> @rultor release, tag=`1.4`

@olenagerasimova Done! FYI, the full log is [here](https://www.rultor.com/t/24458-839532547) (took me 10min)