Write obsoletes tag to primary
artipie/rpm-adapter pull request #505
Opened 2022-01-26 14:49 UTC by olenagerasimova

CLoses #503 
Added obsoletes tag to primary xml and corresponding tests. Also, exclude `/boot` folder from files list.

2022-01-26 15:04 UTC, genryxy commented
@olenagerasimova build is failing now

2022-01-26 17:54 UTC, genryxy requested changes
@olenagerasimova thanks, one comment

2022-01-26 17:54 UTC, genryxy commented on src/main/java/com/artipie/rpm/meta/XmlEventPrimary.java
> +                    || name.startsWith("/boot") || name.startsWith("/boot/")
the first condition includes the second one

2022-01-27 06:13 UTC, olenagerasimova commented
@genryxy thanks, fixed

2022-01-27 06:36 UTC, genryxy approved these changes
@olenagerasimova thanks, looks good to me

2022-01-27 06:54 UTC, merged