Write conflicts tag into primary xml
artipie/rpm-adapter pull request #511
Opened 2022-01-31 07:01 UTC by olenagerasimova

Closes #508 
Added conflicts list into primary xml and corresponding tests.

2022-01-31 10:57 UTC, g4s8 requested changes
@olenagerasimova thanks, please check one comment

2022-01-31 10:57 UTC, g4s8 commented on src/main/java/com/artipie/rpm/meta/XmlEventPrimary.java
> +                continue;
Is it possible to cover this logic in test too?

2022-02-01 06:33 UTC, olenagerasimova commented
@g4s8 thanks, added test

2022-02-02 07:44 UTC, g4s8 approved these changes
@olenagerasimova thanks

2022-02-02 07:50 UTC, merged