feat: optimization of adapter code
artipie/rpm-adapter pull request #551
Opened 2023-06-15 11:08 UTC by dgarus

part of #550 550

2023-06-15 13:05 UTC, olenagerasimova requested changes
@dgarus one suggestion, please, check

2023-06-15 13:08 UTC, dgarus commented on src/main/java/com/artipie/rpm/RpmMetadata.java
> +                    Append.setPrimaryPckg(temp, res, primary).run();
We should use this thread too.

2023-06-15 13:13 UTC, olenagerasimova commented on src/main/java/com/artipie/rpm/RpmMetadata.java
> +                    Append.setPrimaryPckg(temp, res, primary).run();
hm, I see, maybe we change method return type to `void`? Runnable is not required and seems confusing in such implementation

2023-06-16 06:02 UTC, olenagerasimova approved these changes

2023-06-16 06:02 UTC, merged